build_from:
  amd64: ghcr.io/home-assistant/amd64-base-alpine:3.19
  aarch64: ghcr.io/home-assistant/aarch64-base-alpine:3.19
  armv7: ghcr.io/home-assistant/armv7-base-alpine:3.19
args:
  NETCLIENT_VERSION: "0.30.0"
