name: "Netmaker Netclient"
description: "Connects Home Assistant to a Netmaker WireGuard network via enrollment token"
version: "1.5.1"
slug: "netclient"
url: "https://github.com/simonreufsteck/HA_Addons"
arch:
  - aarch64
  - amd64
  - armv7
privileged:
  - NET_ADMIN
  - NET_RAW
  - SYS_MODULE
  - SYS_ADMIN
host_network: true
map:
  - config:rw
options:
  token: ""
  hostname: "homeassistant"
  verbosity: 0
schema:
  token: "str"
  hostname: "str?"
  verbosity: "int(0,4)?"
startup: system
boot: auto
